name: Storybook Deployment

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - develop
    paths:
      - '**/*.stories.tsx'
      - '**/*.stories.ts'

jobs:
  storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if PR just opened
        id: check_pr_opened
        run: |
          if [[ "${{ github.event.action }}" == "opened" ]]; then
            echo "pr_just_opened=true" >> $GITHUB_OUTPUT
          else
            echo "pr_just_opened=false" >> $GITHUB_OUTPUT
          fi

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}-storybook

      - name: Dependency install
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Publish to Chromatic
        id: chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment PR
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const prJustOpened = '${{ steps.check_pr_opened.outputs.pr_just_opened }}' === 'true';
            const storybookUrl = '${{ steps.chromatic.outputs.storybookUrl }}';

            let commentBody;
            if (prJustOpened) {
              commentBody = `🎉 PR opened! Storybook deployed.\n\n🚀 Storybook URL: ${storybookUrl}`;
            } else {
              commentBody = `📚 Stories updated! Storybook redeployed.\n\n🚀 Storybook URL: ${storybookUrl}`;
            }

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });
